stages:
- deploy

deploy:
    stage: deploy
    only:
    - master
    script:
    - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v14.2.0/bin
    - npm install
    - npm run build
    - cp -r dist/* /var/www/$CI_PROJECT_NAME/htdocs/
    cache:
        paths:
        - node_modules/

integration-test:
    stage: deploy
    only:
    - pre_prod
    tags:
    - backend
    script:
    - cd /srv/aip
    - git pull
    - chown -R aip:www-data htdocs && find . -type d -mmin -60 -exec chmod 775 {} \; && find . -type f -mmin -60 -exec chmod 664 {} \;
    - docker exec -i aip_php7.2_1 bash -c 'php htdocs/vendor/bin/bim up --force'

integration:
    stage: deploy
    only:
    - prod
    tags:
    - backend
    script:
    - ssh -t -p 2323 root@193.124.206.206 "cd /var/www/indparks.ru; git checkout prod; git pull; php htdocs/vendor/bin/bim up --force; bash /var/www/chmod.sh"

